# Plan
* Experiment with pcf and cmf limit difference
* Try calculating a trajectory with a starting point and the same trajectory from a different starting point. Then calculate the shift and make sure the results are the same.
* Try going straight down or to a different quadrant. Then try it from a starting point at the relevant quadrant

In [9]:
from ramanujantools.cmf.known_cmfs import pFq
import sympy as sp

import matplotlib.pyplot as plt
import numpy as np
from sympy import mobius_transform
%matplotlib notebook
x0, x1, y0, n, x, y, z = sp.symbols('x0 x1 y0 n x y z')
pi_cmf = pFq(2, 1, sp.Rational(1, 2))
# pi_cmf.matrices

def unpack_coord_to_dict(x, y, z):
    return {x0: x, x1: y, y0: z}

## First:
 Experiment with pcf and cmf limit difference

In [10]:
start = {x0: sp.Rational(1, 2), x1: sp.Rational(1, 2), y0: sp.Rational(3, 2)}
direction = {x0: 1, x1: 0, y0: 1}

trajectory = pi_cmf.trajectory_matrix(direction, start)
trajectory

Matrix([
[         (2*n + 1)/(2*n),                    (-2*n - 1)/(4*n)],
[(-2*n - 1)/(n*(2*n - 1)), (2*n + 1)*(4*n + 1)/(2*n*(2*n - 1))]])

Show the pcf representation and limit

In [11]:
pcf = trajectory.as_pcf().pcf
# print(f'{pcf} - \t {pcf.limit(2000).as_float()}')
lim = pi_cmf.limit(direction, 10, start)
# print(f'{lim} - \t {lim.as_float()}')

_____________________________

In [5]:
s1 = {x0: sp.Rational(1, 2), x1: sp.Rational(1, 2), y0: sp.Rational(1, 2)}
s2 = {x0: sp.Rational(1, 2), x1: sp.Rational(1, 2), y0: sp.Rational(3, 2)}
d1 = {x0: 2, x1: 0, y0: 1}
t1 = pi_cmf.trajectory_matrix(d1, s1)
t2 = pi_cmf.trajectory_matrix(d1, s2)
un = pi_cmf.trajectory_matrix({x0: 0, x1: 0, y0: 1}, s1)
unp = pi_cmf.trajectory_matrix({x0: 0, x1: 0, y0: 1}, {x0: sp.Rational(5, 2), x1: sp.Rational(1, 2), y0: sp.Rational(3, 2)})

# print((t1 * unp).applyfunc(sp.expand))
# print()
# print((un * t2).applyfunc(sp.expand))
print(((t1 * unp).applyfunc(sp.expand) - (un * t2).applyfunc(sp.expand)).simplify())
# print((un * t2).applyfunc(sp.expand))

# print(t1)
# print(t2)

Matrix([
[ (-12*n**3 + 4*n**2 + 3*n - 1)/(n*(16*n**4 - 64*n**3 + 83*n**2 - 41*n + 6)), (32*n**4 - 12*n**3 - 12*n**2 + 3*n + 1)/(2*n*(16*n**4 - 64*n**3 + 83*n**2 - 41*n + 6))],
[2*(12*n**3 - 4*n**2 - 3*n + 1)/(n*(16*n**4 - 64*n**3 + 83*n**2 - 41*n + 6)),  (-32*n**4 + 12*n**3 + 12*n**2 - 3*n - 1)/(n*(16*n**4 - 64*n**3 + 83*n**2 - 41*n + 6))]])


In [6]:
pcf1 = t1.as_pcf().pcf
pcf2 = t2.as_pcf().pcf
print(pcf1)
print(pcf2)

PCF(-8*n, -16*n**2 + 16*n - 3)
PCF(8*n, -16*n**2 + 16*n - 3)


In [7]:
l1 = pcf1.limit(2000).as_float()
l2 = pcf2.limit(2000).as_float()
print(l1)
print(l2)

0.98477
-0.98477


In [8]:
# cmf_l1 = pi_cmf.limit(d1, 100, s2)
# cmf_l1.as_float()

In [9]:
an = sp.Matrix([[0, n**2], [1, 2*n+1]])
bn = sp.Matrix([[0, n*(n+2)], [1, 2*n+3]])
un = sp.Matrix([[n, n**2], [1, 3*n+2]])

print((an * un.subs({n: n+1})).applyfunc(sp.expand))
print((un * bn).applyfunc(sp.expand))

mat = sp.eye(2)
depth = 1000
for i in range(1, depth+1):
    mat *= an.subs({n: i})
# print(mat)

print((mat[0, 1] / mat[1, 1]).evalf())

# print(un.subs({n: 1}).inv() * mat * un.subs({n: 11}))

mat = sp.eye(2)
for i in range(1, depth+1):
    mat *= bn.subs({n: i})

# print(mat)

print((mat[0, 1] / mat[1, 1]).evalf())

Matrix([[n**2, 3*n**3 + 5*n**2], [3*n + 2, 7*n**2 + 15*n + 6]])
Matrix([[n**2, 3*n**3 + 5*n**2], [3*n + 2, 7*n**2 + 15*n + 6]])
0.273239544735163
0.503876787768217


-----------------------------------------

In [10]:
s3 = {x0: sp.Rational(1, 2), x1: sp.Rational(1, 2), y0: sp.Rational(3, 2)}
d2 = {x0: 0, x1: -1, y0: 0}
t3 = pi_cmf.trajectory_matrix(d2, s3)
t3

Matrix([
[(4*n - 1)/(4*n), (1 - 2*n)/(8*n)],
[        1/(2*n), (2*n - 1)/(4*n)]])

In [11]:
pcf3 = t3.as_pcf().pcf
print(pcf3)

PCF(3*n + 1, n*(1 - 2*n))


In [12]:
l3 = pcf3.limit(2000).as_float()
print(l3)

0.636619772367581343075535053490057448137838582961825794990669376235587190536906140360455211065012343824291370907031832147571647384458314611511869642926799356916959867749636310292310985587701230754869571584869590646773449560966894516047329520456890799022863761847560347610695824481957643747751376342114892399785773600994689390957838443593292387132299624667945851218797794608751526299146267856964155983496557394439935472396799849771502340684715433724470075068642186190147952038957841459037335072237209977986541221308627102012881299111265588664091786992478392663362424067212143992535647949995331146617741119160122512114621742020823709395414442994343495044485164629512


Now try with negative starting point

In [13]:
s3 = {x0: sp.Rational(-1, 2), x1: sp.Rational(1, 2), y0: sp.Rational(3, 2)}
d2 = {x0: 0, x1: -1, y0: 0}
t3 = pi_cmf.trajectory_matrix(d2, s3)

In [14]:
pcf3 = t3.as_pcf().pcf
print(pcf3)

PCF(3*n + 2, n*(1 - 2*n))


In [15]:
l3 = pcf3.limit(2000).as_float()
print(l3)

1.75193839388410866120390970151145387925039800680574156364047095013998288704371099513451675188354457199145710872079989405748427661078417644683668979299681908322901708294588468135528469895057444351680251738846836967682410931496507355658971837714483609757689299018251052573114396159178649800157454359492070230828574565213615106154661335605444798065351312685127002522291537947911496885492380345134926517866039224943804926369599145265125495390312045041234119885244096163806776556255515666265335161756764286856075774744954420406993653531679610563904636444568694576550875105132027431529456986355329948918859667308086225466390373008543229654557523803535606116803378482418033084


## Conclusions:
1. Starting with y<0 axis where x is not 0 will collapse to 0 or blowup to inf.
2. Starting with y<0 axis where x is 0 will give pi related things.
3. Crossing y will give division by zero unless or some constant if x != 0.

Well... no. I am not sure why it behaves like this and it doesn't seem to be coherent. Lets try again...

In [12]:
import numpy as np
import matplotlib.pyplot as plt


def generate_starting_points(grid_size):
    """Generate a grid of starting points in 3D space."""
    x = np.linspace(-2, 2, grid_size)
    y = np.linspace(-2, 2, grid_size)
    z = np.linspace(-2, 2, grid_size)
    X, Y, Z = np.meshgrid(x, y, z)
    return np.vstack([X.ravel(), Y.ravel(), Z.ravel()]).T


def calculate_limit(start_points, direction: dict):
    """Apply a matrix transformation along a given direction."""
    limits = []
    categories = []

    labels = ['rational', 'irrational', 'error']

    # return np.array(categories)
    for p in start_points:
        delta = -10
        try:
            start = {x0: sp.Rational(p[0]), x1: sp.Rational(p[1]), y0: sp.Rational(p[2])}
            trajectory = pi_cmf.trajectory_matrix(direction, start)
            pcf = trajectory.as_pcf().pcf
            limit = pcf.limit(2000).as_float()
            delta = pcf.delta(2000)
            limits.append(limit)
            res = limit
        except Exception as e:
            res = 'error'
            limits.append(None)
        finally:
            category = categorize_value(res if res != 'error' else None, delta)
            categories.append(category)
            print(f'{p}, {labels[category]} -> {res}')
    return limits, categories


def categorize_value(value, delta, small_denom_threshold=1000, zero_threshold=1e-10, inf_threshold=1e10):
    """Categorize values based on their rationality."""
    if value is None:
        return 2  # Error case
    if abs(value) > inf_threshold:
        return 0

    def is_fractional(num):
        return sp.nsimplify(num, tolerance=1e-12).q < 10**6  # Limit denominator size

    from sympy import Rational, continued_fraction
    def is_rational_cf(x, depth=20):
        try:
            return len(continued_fraction(Rational(x))) < depth
        except:
            return True

    if is_rational_cf(value):
        return 0
    return 1
    # if np.isclose(value, round(value), atol=zero_threshold):
    #     return 0
    #
    # if delta > 0:
    #     return 1
    #
    # try:
    #     # Use nsimplify to detect rationals within a tolerance
    #     simplified = sp.nsimplify(value, tolerance=1e-20, rational=True)
    #     if simplified.is_rational:
    #         return 0
    # except Exception:
    #     return 1  # Could not simplify

    # rational_val = sp.Rational(str(value)).limit_denominator(1e6)
    #
    # if rational_val.denominator == 1 or abs(value) < zero_threshold:
    #     return 0
    # if abs(rational_val - value) < 1 / rational_val.denominator:
    #     return 1
    # return 0

Try to map shards:

In [13]:
direction = {x0: 0, x1: 1, y0: 0}

starting_points = generate_starting_points(grid_size=5)
limits, categories = calculate_limit(starting_points, direction)
# categories = categorize_values(limits)
colors = np.array(['blue', 'green', 'red'])  # Whole, Many Decimals, Error

# Plot results
fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot for starting points, colored by category
sc = ax.scatter(starting_points[:, 0], starting_points[:, 1], starting_points[:, 2],
                c=[colors[c] for c in categories], marker='o')

handles = [plt.Line2D([0], [0], marker='o', color='w', markerfacecolor=color, markersize=10) for color in ['blue', 'green', 'red']]
labels = ['rational', 'irrational', 'error']
ax.legend(handles, labels)

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.set_title('3D CMF limit classification')
plt.ion()
plt.show()

[-2. -2. -2.], rational -> 0.0
[-2. -2. -1.], rational -> -6.0
[-2. -2.  0.], rational -> -7.2
[-2. -2.  1.], rational -> -8.7692307692307692307692307692307692307692307692307692307692307692307692307692307692307692307692307692307692308
[-2. -2.  2.], rational -> -10.56
[-1. -2. -2.], rational -> 0.0
[-1. -2. -1.], error -> error
[-1. -2.  0.], rational -> -6.0
[-1. -2.  1.], rational -> -7.5
[-1. -2.  2.], rational -> -9.3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333
[ 0. -2. -2.], rational -> 0.0
[ 0. -2. -1.], error -> error
[ 0. -2.  0.], rational -> 2.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

<IPython.core.display.Javascript object>

----------------------------------
## trying:
1. starting at the (x>0, y>0, z>0) and going towards y < 0
2. starting at the (x>0, y<0, z>0) and going towards y < 0
3. starting at the (x>0, y<0, z>0) and going towards y > 0

In [18]:
s3 = {x0: sp.Rational(1, 2), x1: sp.Rational(1, 2), y0: sp.Rational(3, 2)}
d2 = {x0: -1, x1: -1, y0: 0}
t3 = pi_cmf.trajectory_matrix(d2, s3)
t3

Matrix([
[(2*n - 1)*(10*n - 3)/(8*n**2), (2*n - 1)**2*(4*n - 3)/(16*n**2)],
[           (4*n - 1)/(4*n**2),            (2*n - 1)**2/(8*n**2)]])

In [19]:
pcf = t3.as_pcf().pcf
lim = pcf.limit(2000).as_float()
print(pcf)
print(lim)

PCF(48*n**3 + 36*n**2 - 2*n - 2, n**2*(-64*n**4 + 96*n**3 + 12*n**2 - 52*n + 15))
-1.909859317102744029226605160470172344413515748885477384972008128706761571610718421081365633195037031472874112721095496442714942153374943834535608928780398070750879603248908930876932956763103692264608714754608771940320348682900683548141988561370672397068591285542681042832087473445872931243254129026344677199357320802984068172873515330779877161396898874003837553656393383826254578897438803570892467950489672183319806417190399549314507022054146301173410225205926558570443856116873524377112005216711629933959623663925881306038643897333796765992275360977435177990087272201636431977606943849985993439853223357060840194888130772666194855730561466392513772176533176854687596816557495741781135749127768839529300294003573118285068682833561421578302520195812952251097739274886737474437757809070981510297222538904890674410458319281626605909689089694992671172955424798501863952689767781268912299057564879944628488399710891892494

It seems that when x0 is not positive we get an error or a rational number (tried with `x in [0, 1, 2, -1, -2, -5, -3]`)

The problem is with the different starting points. The above holds for $(1/2, 1/2, 3/2)$ but for $(1/2, 3/2$ or $2, 3/2)$ it behaves a bit different and changing x to negative numbers did not help - I guess because somewhere there is a 0 det.
Also when tried with $(1/2, 1, 3/2)$ it worked for negative numbers of x only. x=0 gave a whole number.

$\Rightarrow$ I think in general we cannot cross y=0 in general as speculated

As I understood it - going from $(x>0, y>0, z>0)$ to $(x>0, y<0, z>0)$ doesn't work. but going from $(x>0, y>0, z>0)$ to $(x<0, y<0, z>0)$ does work!

In [20]:
s3 = {x0: sp.Rational(1, 2), x1: sp.Rational(-1, 2), y0: sp.Rational(3, 2)} #
d2 = {x0: -1, x1: -1, y0: 0} # 0
t3 = pi_cmf.trajectory_matrix(d2, s3)
t3

Matrix([
[(20*n**2 + 4*n - 1)/(8*n*(n + 1)), (2*n - 1)*(2*n + 1)*(4*n - 1)/(16*n*(n + 1))],
[          (4*n + 1)/(4*n*(n + 1)),            (2*n - 1)*(2*n + 1)/(8*n*(n + 1))]])

In [21]:
pcf = t3.as_pcf().pcf
lim = pcf.limit(2000).as_float()
print(pcf)
print(lim)

PCF(48*n**3 + 108*n**2 + 66*n + 9, n*(-64*n**5 - 96*n**4 + 44*n**3 + 84*n**2 - 7*n - 15))
8.75969196942054330601954850755726939625199003402870781820235475069991443521855497567258375941772285995728554360399947028742138305392088223418344896498409541614508541472942340677642349475287221758401258694234184838412054657482536778294859188572418048788446495091255262865571980795893249000787271797460351154142872826068075530773306678027223990326756563425635012611457689739557484427461901725674632589330196124719024631847995726325627476951560225206170599426220480819033882781277578331326675808783821434280378873724772102034968267658398052819523182222843472882754375525660137157647284931776649744594298336540430995280774920750346999632021392962262882458133859997769925804797773403957420532778115609924882580869952943608038924897705676063737171036448120967886290278696125035087645869925017034556288189768378939593395430005974748530359629803074207369916237069010602896021358243778882092470420059009690083723465530

Now tried to play a bit with the space $(x>0, y<0, z>0)$ but it seems like a dull one because I always got a whole number or division by zero error.

Also it did seem to work to try to pass to the other sub-space $(x<0, y<0, z>0)$

-------------------------------

## Conclusions
Because multiplying by the relevant trajectory matrix i.e. walking to the limit is the same as applying a mobius transform when encountering zero determinant matrices we get a constant! This gives us instead of meaningful numbers some not interesting rational constants...

Let us choose matrix A such that $|A|=0$.

$\begin{align*}A=\left(\begin{matrix} a & b \\ ca & cb\end{matrix}\right)(z)=\frac{az+b}{caz+cb}=\frac{1}{c}\end{align*}$

Let's try to see when in the CMF the atomic trajectory matrices have determinant 0.

In [21]:
mats = pi_cmf.matrices
Mx = mats[x0]
My = mats[x1]
Mz = mats[y0]

In [22]:
Mx

Matrix([
[   1,                          x1],
[1/x0, 1 + (x0 + x1 - 2*y0 + 2)/x0]])

In [23]:
My

Matrix([
[   1,                          x0],
[1/x1, 1 + (x0 + x1 - 2*y0 + 2)/x1]])

In [24]:
Mz

Matrix([
[y0*(-x0 - x1 + y0)/(x0*x1 - x0*y0 - x1*y0 + y0**2), x0*x1*y0/(x0*x1 - x0*y0 - x1*y0 + y0**2)],
[                y0/(x0*x1 - x0*y0 - x1*y0 + y0**2),   -y0**2/(x0*x1 - x0*y0 - x1*y0 + y0**2)]])

In [26]:
sp.solve(Mx.det())

[{x0: y0 - 1}]

In [27]:
sp.solve(My.det())

[{x1: y0 - 1}]

In [28]:
sp.solve(Mz.det())

[{y0: 0}]

In [14]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Create a grid of (x, y) points
x_vals = np.linspace(-5, 5, 10)
y_vals = np.linspace(-5, 5, 10)
X, Y = np.meshgrid(x_vals, y_vals)

# Plot the figure
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

def plot_plain(Z, color):
    ax.plot_surface(X, Y, Z, color=color, alpha=0.5)

plot_plain(X+1, 'red')
plot_plain(Y+1, 'blue')
plot_plain(np.zeros_like(X), 'green')

handles = [plt.Line2D([0], [0], marker='o', color='w', markerfacecolor=color, markersize=10) for color in ['red', 'blue', 'green']]
labels = ['Z=X+1 (Mx)', 'Z=Y+1 (My)', 'Z=0 (Mz)']
ax.legend(handles, labels)

# Labels
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
plt.title('the shards of Pi CMF')

plt.show()

<IPython.core.display.Javascript object>

## Notes about co-boundary
Coboundry definition: $A_n \cdot U_{n+1} = U_n \cdot B_n \Rightarrow A_1 \cdot A_2 \dots A_n = U_1 \cdot B_1 \cdot B_2 \dots B_n \cdot U_{n+1}^{-1}$

----------------------------

## Up-next: validation
* Choose points on the 0 determinant plains and ensure det = 0
* Check what happens to the limit when passing through a plain.

In [15]:
plain_transform = np.array([[1, 0, 0], [0, 1, 0], [-1, -1, -1]])
dlim = 2

def cartesian_product(*arrays):
    """Computes the Cartesian product of multiple arrays."""
    grids = np.meshgrid(*arrays, indexing="ij")  # Create coordinate grids
    flattened = [grid.ravel() for grid in grids]  # Flatten each grid
    return np.column_stack(flattened)  # Stack them into a 2D array

def generate_vector_in_octant(point, magnitude_range=(1, 5)):
    """
    Generates a vector that starts at 'point' and points in a direction
    that stays within the same octant.

    Args:
        point (np.array): A 3D point (x, y, z).
        magnitude_range (tuple): Min and max range for vector magnitude.

    Returns:
        np.array: A direction vector following the octant rule.
    """
    # Generate random magnitudes for the direction vector
    magnitude = np.random.uniform(magnitude_range[0], magnitude_range[1], size=3)

    # Ensure the vector has the same sign as the point
    direction = np.sign(point) * magnitude  # Sign multiplication

    return direction

piece = list(range(-dlim, dlim+1))
piece.remove(0)
points = cartesian_product(piece, piece, piece)
# print(points)

transformed = []
directions = []
xs = []
ys = []
zs = []
for p in points:
    directions.append(np.array(plain_transform @ generate_vector_in_octant(p, magnitude_range=(1, 1))).astype(np.int64))
    p = plain_transform @ np.array(p)

    p = np.array(p).astype(np.int64)
    transformed.append(p)
    xs.append(p[0])
    ys.append(p[1])
    zs.append(p[2])

In [16]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def plot_shards(plot_borders=True, plot_yxz_hat=True, plot_points=False, plot=True):
    # Create a grid of (x, y) points
    x_vals = np.linspace(-5, 5, 10)
    y_vals = np.linspace(-5, 5, 10)
    X, Y = np.meshgrid(x_vals, y_vals)

    # Plot the figure
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    def plot_plain(Z, color):
        ax.plot_surface(X, Y, Z, color=color, alpha=0.5)

    if plot_borders:
        plot_plain(X+1, 'red')
        plot_plain(Y+1, 'blue')
        plot_plain(np.zeros_like(X), 'green')

        handles = [plt.Line2D([0], [0], marker='o', color='w', markerfacecolor=color, markersize=10) for color in ['red', 'blue', 'green']]
        labels = ['Z=X+1 (Mx)', 'Z=Y+1 (My)', 'Z=0 (Mz)']
        ax.legend(handles, labels)

    # Labels
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    plt.title('the shards of Pi CMF')

    if plot_yxz_hat:
        # Define the point and vector
        origin = np.array([-1, -1, 0])

        x_hat = np.array([1, 0, 0]) * 3
        y_hat = np.array([0, 1, 0]) * 3
        z_hat = np.array([-1, -1, -1])
        z_hat = z_hat / np.linalg.norm(z_hat) * 3

        # Plot the vector using quiver
        ax.quiver(*origin, *x_hat, color='red', linewidth=5, arrow_length_ratio=0.1)
        ax.quiver(*origin, *y_hat, color='blue', linewidth=5, arrow_length_ratio=0.1)
        ax.quiver(*origin, *z_hat, color='green', linewidth=5, arrow_length_ratio=0.1)

        ax.scatter([xs[0]], [ys[0]], [zs[0]], color='b', marker='o')
        ax.quiver(*[xs[0], ys[0], zs[0]], *directions[0], color='red', linewidth=3, arrow_length_ratio=0.1)

        if plot_points:
            ax.scatter(xs, ys, zs, color='b', marker='o')
            if plot_points:
                for p, d in zip(transformed, directions):
                    ax.quiver(*p, *d, color='red', linewidth=5, arrow_length_ratio=0.1)
                    # try:
                    #     # tm = pi_cmf.trajectory_matrix(unpack_coord_to_dict(*(-d)), unpack_coord_to_dict(*p))
                    #     # pcf = tm.as_pcf().pcf
                    #     # print(pcf.limit(500).as_float())
                    # except:
                    #     pass
    axis_limit = 5
    ax.set_xlim([-axis_limit, axis_limit])
    ax.set_ylim([-axis_limit, axis_limit])
    ax.set_zlim([-axis_limit, axis_limit])

    if plot:
        plt.show()
    return ax

In [17]:
plot_shards(plot_borders=True, plot_yxz_hat=True, plot_points=True)

<IPython.core.display.Javascript object>

<Axes3D: title={'center': 'the shards of Pi CMF'}, xlabel='X', ylabel='Y', zlabel='Z'>

In [18]:
print(points[0])
print(directions[0])

[-2 -2 -2]
[-1 -1  3]


Let's make sure the matrix on the border has det = 0.

In [130]:
ax = plot_shards(plot_borders=True, plot_yxz_hat=False, plot_points=False, plot=False)

start = unpack_coord_to_dict(-2, -2, -1)
trajectory = unpack_coord_to_dict(0, 0, 1)
tm = pi_cmf.trajectory_matrix(trajectory, start)

ax.scatter(-2, -2, -1, color='b', marker='o')
ax.quiver(-2, -2, -1, 0, 0, 1, color='red', linewidth=3, arrow_length_ratio=0.1)

plt.show()

<IPython.core.display.Javascript object>

In [148]:
from ramanujantools import Matrix

curr_mat = tm.walk(trajectory, 3, start)
print(tm.as_pcf().pcf.limit(4000).as_float())
det = curr_mat.det()
sol = sp.solve(det)
# current matrix and its det
print(curr_mat)
print(det)
print(curr_mat.subs({n: 1}))

# solution to det == 0 and substitute for number of steps
walking = Mz.subs(unpack_coord_to_dict(-2, -2, -1)) * Mz.subs(unpack_coord_to_dict(-2, -2, 0)) * Mz.subs(unpack_coord_to_dict(-2, -2, 1))
# print(walking)

# creating CMF using trajectory matrix
matrix = tm
U = Matrix([[matrix[1, 0], -matrix[0, 0]], [0, 1]])
Uinv = Matrix([[1, matrix[0, 0]], [0, matrix[1, 0]]])
commutated = U * matrix * Uinv.subs({n: n + 1})
reduced = (commutated / commutated[1, 0]).simplify() # originally written as reduced = (commuted / commutated[1, 0]).simplify() but it doesn't work somehow

# walk with the original trajectory matrix and the commuted one
# here we still get the zero matrix. Possible explanation - no inflation / deflation of pcf
walking_org = matrix.subs({n: 1}) * matrix.subs({n: 2}) #* matrix.subs({n: 3})
walking_com = commutated.subs({n: 1}) * commutated.subs({n: 2}) * commutated.subs({n: 3})
walking_reduced = reduced.subs({n: 1}) *  reduced.subs({n: 2}) *  reduced.subs({n: 3})

5.17739889912417967
Matrix([
[(n - 2)**3*(n + 4)*(n**2 + 2*n + 8)/n**6,            (n - 2)**3*(4*n**2 + 64)/n**6],
[             (n - 2)**3*(n**2 + 16)/n**6, (4 - n)*(n - 2)**3*(n**2 - 2*n + 8)/n**6]])
-1 + 12/n - 60/n**2 + 160/n**3 - 240/n**4 + 192/n**5 - 64/n**6
Matrix([
[-55, -68],
[-17, -21]])


In [149]:
walking_org

Matrix([
[0, 0],
[0, 0]])

In [150]:
walking_com

Matrix([
[0, 0],
[0, 0]])

In [151]:
reduced

Matrix([
[0, (n**2 - 3*n + 2)/(n**2 + 2*n + 1)],
[1,        5*(n - 1)/(n**2 + 2*n + 1)]])

In [152]:
walking_reduced

Matrix([
[0, 0],
[0, 0]])

In [164]:
pcf = tm.as_pcf().pcf
pcf_matrix = pcf.M()
pcf_matrix

Matrix([
[0, n**2],
[1,    5]])

In [165]:
pcf.M().subs({n: 1}) * pcf.M().subs({n: 2}) * pcf.M().subs({n: 3}) # this is none zero!

Matrix([
[ 5,  34],
[29, 190]])

In [166]:
pcf.M().det()

-n**2

# Conclusion:
* The process of inflation and deflation when converting a matrix into a PCF is causing it to lose its 0 determinant in the path and prevents it from becoming the zero matrix.
* I am still not sure what happens in walk and why does it behave differently.
* The limits in different regions of the newly seperated 3D space vary and consist of different constants.
 * When passing through a border sometimes getting meaningful results of other constants and sometimes just garbage.

## Up-next: further investigation
* Check for more points, what happens when crossing to other borders? (maybe automate the geometry? it might be helpful later ...)
* Check what constants relate to each octant. this must be done manually but data gathering could be automated.